import type {
  Achievement,
  ClassGroup,
  DemoStore,
  Exam,
  ExamQuestion,
  Profile,
  Question,
  StudentAchievement,
  StudentAnswer,
  StudentAttempt,
} from "@/lib/types";

const now = new Date().toISOString();

export const demoClasses: ClassGroup[] = [
  { id: "class-1", name: "2A EM", year: "2026", active: true, created_at: now },
  { id: "class-2", name: "2B EM", year: "2026", active: true, created_at: now },
  { id: "class-3", name: "3A EM", year: "2026", active: true, created_at: now },
];

export const demoProfiles: Profile[] = [
  {
    id: "admin-1",
    email: "admin@santamarcelina.edu.br",
    full_name: "Coordenação Base ENEM",
    role: "admin",
    class_id: null,
    active: true,
    created_at: now,
  },
  {
    id: "student-1",
    email: "ana.beatriz@santamarcelina.edu.br",
    full_name: "Ana Beatriz",
    role: "student",
    class_id: "class-1",
    active: true,
    created_at: now,
  },
  {
    id: "student-2",
    email: "marina.lima@santamarcelina.edu.br",
    full_name: "Marina Lima",
    role: "student",
    class_id: "class-1",
    active: true,
    created_at: now,
  },
  {
    id: "student-3",
    email: "carlos.silva@santamarcelina.edu.br",
    full_name: "Carlos Silva",
    role: "student",
    class_id: "class-2",
    active: true,
    created_at: now,
  },
  {
    id: "student-4",
    email: "pedro.costa@santamarcelina.edu.br",
    full_name: "Pedro Costa",
    role: "student",
    class_id: "class-2",
    active: true,
    created_at: now,
  },
  {
    id: "student-5",
    email: "joana.ribeiro@santamarcelina.edu.br",
    full_name: "Joana Ribeiro",
    role: "student",
    class_id: "class-3",
    active: true,
    created_at: now,
  },
];

export const demoQuestions: Question[] = [
  {
    id: "q-1",
    statement: "Em uma leitura de gráfico, a variação percentual de uma grandeza é dada por...",
    option_a: "diferença entre o maior e o menor valor",
    option_b: "razão entre variação e valor inicial",
    option_c: "soma dos valores observados",
    option_d: "produto entre a média e o desvio",
    option_e: "mediana da distribuição",
    correct_option: "B",
    explanation: "A variação percentual relaciona a diferença ao valor inicial.",
    exam_year: 2024,
    knowledge_area: "Matemática",
    subject: "Matemática",
    topic: "Porcentagem",
    difficulty: "media",
    active: true,
    created_at: now,
  },
  {
    id: "q-2",
    statement: "A função da linguagem predominante em um texto publicitário é...",
    option_a: "emotiva",
    option_b: "referencial",
    option_c: "poética",
    option_d: "conativa",
    option_e: "metalinguística",
    correct_option: "D",
    explanation: "Textos publicitários buscam persuadir o leitor.",
    exam_year: 2023,
    knowledge_area: "Linguagens",
    subject: "Português",
    topic: "Funções da linguagem",
    difficulty: "facil",
    active: true,
    created_at: now,
  },
  {
    id: "q-3",
    statement: "A Revolução Industrial alterou principalmente a relação entre...",
    option_a: "campo e cidade",
    option_b: "alfabetização e imprensa",
    option_c: "religião e ciência",
    option_d: "nobreza e clero",
    option_e: "língua e gramática",
    correct_option: "A",
    explanation: "A industrialização intensificou a urbanização e o êxodo rural.",
    exam_year: 2022,
    knowledge_area: "Ciências Humanas",
    subject: "História",
    topic: "Revolução Industrial",
    difficulty: "media",
    active: true,
    created_at: now,
  },
  {
    id: "q-4",
    statement: "A base da cadeia alimentar é formada, em geral, por...",
    option_a: "consumidores terciários",
    option_b: "decompositores",
    option_c: "produtores",
    option_d: "predadores de topo",
    option_e: "parasitas",
    correct_option: "C",
    explanation: "Os produtores transformam energia para sustentar a cadeia.",
    exam_year: 2024,
    knowledge_area: "Ciências da Natureza",
    subject: "Biologia",
    topic: "Ecologia",
    difficulty: "facil",
    active: true,
    created_at: now,
  },
  {
    id: "q-5",
    statement: "O gráfico de posição versus tempo com inclinação positiva constante representa...",
    option_a: "repouso",
    option_b: "movimento uniforme",
    option_c: "aceleração negativa",
    option_d: "movimento circular",
    option_e: "variação instantânea nula",
    correct_option: "B",
    explanation: "Inclinação constante em s x t indica velocidade constante.",
    exam_year: 2021,
    knowledge_area: "Ciências da Natureza",
    subject: "Física",
    topic: "Cinemática",
    difficulty: "media",
    active: true,
    created_at: now,
  },
];

for (let i = 6; i <= 20; i += 1) {
  demoQuestions.push({
    id: `q-${i}`,
    statement: `Questão fictícia ENEM ${i}: interpretação, análise e raciocínio contextual.`,
    option_a: `Alternativa A ${i}`,
    option_b: `Alternativa B ${i}`,
    option_c: `Alternativa C ${i}`,
    option_d: `Alternativa D ${i}`,
    option_e: `Alternativa E ${i}`,
    correct_option: ["A", "B", "C", "D", "E"][i % 5] as Question["correct_option"],
    explanation: "Resposta comentada de forma resumida para o estudante revisar o conteúdo.",
    exam_year: 2020 + (i % 5),
    knowledge_area: [
      "Linguagens",
      "Ciências Humanas",
      "Ciências da Natureza",
      "Matemática",
    ][i % 4],
    subject: ["Português", "História", "Biologia", "Matemática"][i % 4],
    topic: ["Leitura", "Urbanização", "Ecologia", "Funções"][i % 4],
    difficulty: ["facil", "media", "dificil"][i % 3] as Question["difficulty"],
    active: true,
    created_at: now,
  });
}

export const demoExams: Exam[] = [
  {
    id: "exam-1",
    title: "Simulado Base ENEM - Diagnóstico 1",
    description: "Avaliação inicial com foco em leitura, interpretação e resolução básica.",
    knowledge_area: null,
    exam_year: 2024,
    time_limit_minutes: 60,
    active: true,
    created_at: now,
  },
  {
    id: "exam-2",
    title: "Simulado Base ENEM - Revisão 2",
    description: "Simulado misto com foco em recuperação de dificuldades.",
    knowledge_area: null,
    exam_year: 2025,
    time_limit_minutes: 50,
    active: true,
    created_at: now,
  },
];

export const demoExamQuestions: ExamQuestion[] = [
  ...demoQuestions.slice(0, 10).map((question, index) => ({
    id: `eq-1-${index + 1}`,
    exam_id: "exam-1",
    question_id: question.id,
    position: index + 1,
  })),
  ...demoQuestions.slice(5, 15).map((question, index) => ({
    id: `eq-2-${index + 1}`,
    exam_id: "exam-2",
    question_id: question.id,
    position: index + 1,
  })),
];

export const demoAttempts: StudentAttempt[] = [
  {
    id: "attempt-1",
    student_id: "student-1",
    exam_id: "exam-1",
    started_at: new Date(Date.now() - 1000 * 60 * 78).toISOString(),
    finished_at: new Date(Date.now() - 1000 * 60 * 48).toISOString(),
    total_questions: 10,
    correct_answers: 7,
    score_percent: 70,
    total_time_seconds: 1800,
  },
  {
    id: "attempt-2",
    student_id: "student-2",
    exam_id: "exam-1",
    started_at: new Date(Date.now() - 1000 * 60 * 90).toISOString(),
    finished_at: new Date(Date.now() - 1000 * 60 * 60).toISOString(),
    total_questions: 10,
    correct_answers: 9,
    score_percent: 90,
    total_time_seconds: 1800,
  },
];

export const demoAnswers: StudentAnswer[] = [
  {
    id: "answer-1",
    attempt_id: "attempt-1",
    student_id: "student-1",
    question_id: "q-1",
    selected_option: "B",
    is_correct: true,
    time_spent_seconds: 120,
    answered_at: now,
  },
  {
    id: "answer-2",
    attempt_id: "attempt-1",
    student_id: "student-1",
    question_id: "q-2",
    selected_option: "A",
    is_correct: false,
    time_spent_seconds: 100,
    answered_at: now,
  },
  {
    id: "answer-3",
    attempt_id: "attempt-2",
    student_id: "student-2",
    question_id: "q-1",
    selected_option: "B",
    is_correct: true,
    time_spent_seconds: 90,
    answered_at: now,
  },
];

export const demoAchievements: Achievement[] = [
  {
    id: "ach-1",
    name: "Primeira questão respondida",
    description: "Marcou presença na Base ENEM.",
    icon: "sparkles",
    trigger_type: "questions_answered",
    trigger_value: 1,
    active: true,
  },
  {
    id: "ach-2",
    name: "10 questões respondidas",
    description: "Começou a ganhar ritmo.",
    icon: "target",
    trigger_type: "questions_answered",
    trigger_value: 10,
    active: true,
  },
  {
    id: "ach-5",
    name: "50 questões respondidas",
    description: "Volume consistente de treino.",
    icon: "target",
    trigger_type: "questions_answered",
    trigger_value: 50,
    active: true,
  },
  {
    id: "ach-6",
    name: "100 questões respondidas",
    description: "Forte rotina de estudos.",
    icon: "target",
    trigger_type: "questions_answered",
    trigger_value: 100,
    active: true,
  },
  {
    id: "ach-7",
    name: "7 dias seguidos estudando",
    description: "Consistência acima da média.",
    icon: "flame",
    trigger_type: "streak_days",
    trigger_value: 7,
    active: true,
  },
  {
    id: "ach-3",
    name: "70% de acerto geral",
    description: "Bom caminho para a aprovação.",
    icon: "award",
    trigger_type: "score_percent",
    trigger_value: 70,
    active: true,
  },
  {
    id: "ach-8",
    name: "80% de acerto geral",
    description: "Desempenho muito forte.",
    icon: "award",
    trigger_type: "score_percent",
    trigger_value: 80,
    active: true,
  },
  {
    id: "ach-4",
    name: "Primeiro simulado concluído",
    description: "Primeiro passo do ciclo de estudos.",
    icon: "check-circle-2",
    trigger_type: "attempts_finished",
    trigger_value: 1,
    active: true,
  },
  {
    id: "ach-9",
    name: "Melhorando em Matemática",
    description: "Sua base em Matemática está ficando mais forte.",
    icon: "trending-up",
    trigger_type: "math_progress",
    trigger_value: 60,
    active: true,
  },
  {
    id: "ach-10",
    name: "Melhorando em Natureza",
    description: "Sua base em Natureza está crescendo.",
    icon: "trending-up",
    trigger_type: "nature_progress",
    trigger_value: 60,
    active: true,
  },
];

export const demoStudentAchievements: StudentAchievement[] = [
  { id: "sa-1", student_id: "student-1", achievement_id: "ach-1", unlocked_at: now },
  { id: "sa-2", student_id: "student-1", achievement_id: "ach-4", unlocked_at: now },
  { id: "sa-3", student_id: "student-2", achievement_id: "ach-1", unlocked_at: now },
  { id: "sa-4", student_id: "student-2", achievement_id: "ach-2", unlocked_at: now },
];

export const demoStore: DemoStore = {
  profiles: demoProfiles,
  classes: demoClasses,
  questions: demoQuestions,
  exams: demoExams,
  examQuestions: demoExamQuestions,
  attempts: demoAttempts,
  answers: demoAnswers,
  achievements: demoAchievements,
  studentAchievements: demoStudentAchievements,
};

export const demoCredentials = [
  { email: "admin@santamarcelina.edu.br", password: "Admin123!", role: "admin" as const },
  { email: "ana.beatriz@santamarcelina.edu.br", password: "Aluno123!", role: "student" as const },
  { email: "marina.lima@santamarcelina.edu.br", password: "Aluno123!", role: "student" as const },
  { email: "carlos.silva@santamarcelina.edu.br", password: "Aluno123!", role: "student" as const },
  { email: "pedro.costa@santamarcelina.edu.br", password: "Aluno123!", role: "student" as const },
  { email: "joana.ribeiro@santamarcelina.edu.br", password: "Aluno123!", role: "student" as const },
];
